export default {
    MAIN_PAGE: '/',
    MY_DIAGRAM: '/my-diagram',
    NEW_DIAGRAM: '/new-diagram',
    EDIT_DIAGRAM: '/edit-diagram',
    STUDENT_ASSIGNMENTS: '/assignments',
    EDIT_ASSIGNMENT: '/edit-assignment',
    CREATE_ASSIGNMENT: '/create-assignment',
    PROFESSOR_ASSIGNMENTS: '/professor-assignments',
    REGISTER: '/register',
    LOGIN: '/login',
    UNAUTHORIZED: '/unauthorized',
    NOT_AUTHENTICATED: '/not-authenticated',
    NOT_FOUND: '/not-found',
    CREATE_PLAN: '/create-plan',
    EDIT_PLAN: '/edit-plan',
    PLANS: '/plans',
    GROUPS: '/groups',
    USERS: '/users',
    CHANGE_PASSWORD: '/change-password',
    EDIT_PROFILE: '/edit-profile',
    ALL_ASSIGNMENTS: '/all-assignments'
};